### ISSUE TITLE
Does the tool only support 7.4? I tried 7.0 and 7.5 and both failed.

### ISSUE THREAD

**Issue by hac425xxx** [jhftss/IDA2Obj#1]
Does the tool only support 7.4? I tried 7.0 and 7.5 and both failed.

**Comment by jhftss** [comment]
In theory, 7.0+ is ok. I have tested it on 7.5
Can you provide the failure details ?

**Comment by hac425xxx** [comment]
The ida script uses some old APIs, which are not supported by idapython 7.5.

**Comment by hac425xxx** [comment]
env:
python3 + idapython + ida 7.5

**Comment by jhftss** [comment]
> The ida script uses some old APIs, which are not supported by idapython 7.5.

Yes, I prefered the old API style. And I had put the step 0 (prepare the environment) in README.md:
Set AUTOIMPORT_COMPAT_IDA695 = YES in the idapython.cfg to support the API with old IDA 6.x style.

**Comment by hac425xxx** [comment]
Thank you. I'll try this.

**Comment by hac425xxx** [comment]
it works
