### ISSUE TITLE
I have some questions...

### ISSUE THREAD

**Issue by gitmesam** [jhftss/IDA2Obj#2]
[EN]
a year ago - I also wanted to do such a project, but then many people laughed at me. And so ... now I see him realized by you.

I have a few questions for you:
1.in the objdump.py file
    def AddRelocation (self, va, symIndex, type):
        reloc = Relocation () <----------- what is this function? where is she from? where is it described?
2. There is no problem to "parse" the dll-file (which, by definition, has a relocation table)
and a completely different matter - when we are dealing with an exe file (which has a relocation table cut out)
3. What if your file has no debug symbols? (pdb file).
4. How about making the converter more intelligent - not sticking the whole section into an obj file, but dividing them as they were before the linker? (I do not argue, this is much more difficult - but, this is what I have to do now, doing real reverse engineering) 

[RU]
год назад - тоже захотел сделать такой проект но, тогда многие люди смеялись над о мной. И вот... теперь я вижу его реализованным тобой.

У меня есть к вам несколько вопросов:
1. в файле objdump.py 
    def AddRelocation(self, va, symIndex, type):
        reloc = Relocation()     <-----------что это за функция? откуда она? где она описана?
2. Нет никакой проблемы "распарсить"  dll-файл (у которого по определению сохранена таблица релокаций)
и совсем другое дело - когда мы имеем дело с exe-файлом (у которого вырезана таблица релокаций)
3. Как быть, если у твоего файла - нет отладочных символов? (pdb-файл).
4. Как насчёт того, чтоб сделать конвертер более интеллектуальным - не засовывая всю секцию в obj-файл, а разделяя их так - как они были до linker? (не спорю, это намного труднее - но, это то, что мне приходится делать сейчас, занимаясь реальным реверс-инжинирингом)

**Comment by jhftss** [comment]
Hello, thanks for your attention.
1. "Relocation()" is imported from "cough", which is an obj writer. I just don't want to reinvent the wheels: 
https://github.com/d3dave/cough  (pip install cough)
2.  exe has a relocation table too, no exception at all. However, I don't parse the relocation table manunally, I just reuse the results parsed by IDA Pro.
3. PDB file is not required in my solution.
4. Dividing them as they were before the linker? I think it is impossible in theory.
